---
- name: Instalação do repositório do Zabbix 4.0 LTS
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    state: present
  become: True
- name: Coloca o SELinux como Permissive
  selinux:
    policy: targeted
    state: permissive
  become: True
