---
- name: Adiciona o novo Host no Zabbix Server
  local_action:
    module: zabbix_host
    server_url: http://zabbix-server.rodrigolira.lab/zabbix
    login_user: Admin
    login_password: zabbix
    host_name: Meetup-Zabbix
    visible_name: Meetup-Zabbix
    description: Host de exemplo para o Meetup Zabbix
    host_groups:
      - Linux servers
      - Meetup-Zabbix
    link_templates:
      - Template OS Linux
      - Template Module ICMP Ping
    status: enabled
    state: present
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "192.168.200.91" #{{ hostvars['zabbix-agent.rodrigolira.lab']['ansible_default_ipv4']['address'] }}"
        dns: "" # {{ hostvars['zabbix-agent.rodrigolira.lab'].ansible_fqdn }}
        port: 10050
